theme: jekyll-theme-minimal
title: 'Artificial Intelligence and Machine Learning - Unit 2'
description: '<p style="text-align:left">AA 2021/2022</p>'
logo: /imgs/sapienza_logo.png
show_downloads: false
